# Generated by Django 5.2.13 on 2026-05-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('chatbot', 'Chatbot'), ('workflow', 'Agent Workflow'), ('langchain', 'LangChain Agent'), ('media', 'AI Media'), ('ml', 'Machine Learning'), ('web', 'Web Application')], max_length=50)),
                ('one_sentence_summary', models.CharField(max_length=300)),
                ('business_problem', models.TextField()),
                ('tools_used', models.JSONField(default=list)),
                ('key_features', models.JSONField(default=list)),
                ('role_and_contribution', models.TextField()),
                ('biggest_challenge', models.TextField()),
                ('what_i_learned', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
