# Generated by Django 5.2.13 on 2026-05-04 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('chatbot', 'Chatbot'), ('workflow', 'Agent Workflow'), ('langchain', 'LangChain Agent'), ('media', 'AI Media'), ('ml', 'Machine Learning'), ('web', 'Web Application'), ('quant', 'Quant Finance'), ('equity_research', 'Equity Research'), ('dashboard', 'Dashboard'), ('financial_model', 'Financial Model'), ('case_competition', 'Case Competition'), ('hackathon', 'Hackathon'), ('presentation', 'Presentation')], max_length=50),
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Button label, e.g. "Download Deck" or "View Model"', max_length=100)),
                ('file', models.FileField(upload_to='project_files/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
    ]
